### ISSUE TITLE
Handle write permissions

### ISSUE THREAD

**Issue by sdorra** [cloudogu/smeagol#2]
Smeagol does not handle write permissions. A user which has only read permissions for a repository can edit wiki files and gets an exception on push.

**Comment by sdorra** [comment]
Disable editing in Gollum:

```ruby
Precious::App.set(:wiki_options, { allow_editing: false})
```

[Allow Editing Org Search](https://github.com/search?q=org%3Agollum+allow_editing&type=Code)

**Comment by JBartscher** [comment]
This should be outdated
