### ISSUE TITLE
Please Support BASE64-Pictures

### ISSUE THREAD

**Issue by R3m1n0X** [cloudogu/smeagol#32]
## Quick correction:

The preview of the WYSIWYG editor shows the BASE64 images. When you press Save, they will not be displayed.

## Old post:

> Markdown can format images into BASE64 code.
> 
> As an example:
> 
> `![Hello World](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEYAAAAUCAAAAAAVAxSkAAABrUlEQVQ4y+3TPUvDQBgH8OdDOGa+oUMgk2MpdHIIgpSUiqC0OKirgxYX8QVFRQRpBRF8KShqLbgIYkUEteCgFVuqUEVxEIkvJFhae3m8S2KbSkcFBw9yHP88+eXucgH8kQZ/jSm4VDaIy9RKCpKac9NKgU4uEJNwhHhK3qvPBVO8rxRWmFXPF+NSM1KVMbwriAMwhDgVcrxeMZm85GR0PhvGJAAmyozJsbsxgNEir4iEjIK0SYqGd8sOR3rJAGN2BCEkOxhxMhpd8Mk0CXtZacxi1hr20mI/rzgnxayoidevcGuHXTC/q6QuYSMt1jC+gBIiMg12v2vb5NlklChiWnhmFZpwvxDGzuUzV8kOg+N8UUvNBp64vy9q3UN7gDXhwWLY2nMC3zRDibfsY7wjEkY79CdMZhrxSqqzxf4ZRPXwzWJirMicDa5KwiPeARygHXKNMQHEy3rMopDR20XNZGbJzUtrwDC/KshlLDWyqdmhxZzCsdYmf2fWZPoxCEDyfIvdtNQH0PRkH6Q51g8rFO3Qzxh2LbItcDCOpmuOsV7ntNaERe3v/lP/zO8yn4N+yNPrekmPAAAAAElFTkSuQmCC)`
> 
> On the website: https://word-to-markdown.herokuapp.com/, Word documents can be converted to Markdown and the images contained therein are encoded in BASE64. This eliminates the need for additional maintenance of pictures.
> 
> It would be nice if we could implement this in Smeagol as well.

**Comment by JBartscher** [comment]
You can do that now.
![Example](https://user-images.githubusercontent.com/12815584/190335569-d0aa754f-3324-42ee-b64c-15aa916cf23b.png)
