### ISSUE TITLE
read .smeagol.yml

### ISSUE THREAD

**Issue by sdorra** [cloudogu/smeagol#4]
Currently smeagol checks if the repository contains a _.smeagol.yml_ file, but it does not read the file. Smeagol should read the file and create the [WikiOptions](https://github.com/cloudogu/smeagol/blob/develop/src/main/java/com/cloudogu/wiki/WikiOptions.java) from it.

**Comment by robertauer** [comment]
https://github.com/gollum/gollum/wiki/Gollum-via-Rack#the-options-hash
