### ISSUE TITLE
UML is not rendered in non-editor view

### ISSUE THREAD

**Issue by pczora** [cloudogu/smeagol#64]
When displaying (not editing) a page containing UML, the UML is not rendered by PlantUML. The expected behavior is for Smeagol to render the diagram using PlantUML, as it happens in the editor.

**Comment by JBartscher** [comment]
The wysiwyg editor is not yet capable of "previewing" UML as the UML render happens after the page is saved.
This might be an enhancement of the future but is not a bug by itself.
