### ISSUE TITLE
project discontinued?

### ISSUE THREAD

**Issue by silvio** [cloudogu/smeagol#80]
Sorry for this headline.

Is this project dead? It looks like a neat and nice project with great potential. But I see nearly no development (13.08.), no working with issues, no bugfixing, no working with enhancements ideas etc.

Thanks and bye,
Silvio

**Comment by schnatterer** [comment]
Thanks for asking!

No, this project is definitely not discontinued!
It' still *the* wiki engine within the [Cloudogu Ecosystem](https://cloudogu.com/en/#dogus).

However, we're currently busy with other topics, for example [SCM-Manager v2](https://cloudogu.com/en/blog/scm-manager-collaboration).
As SCMM also powers Smeagol, we'll be updating Smeagol as soon as there is a stable version of SCMMv2.

We're also happy to accept PRs 😀

**Comment by silvio** [comment]
Hi @schnatterer thanks for information. I'm a bit under pressure to find the right wiki for a ooooold mediawiki installation, and smeagold could be our choice.

But yeaa, I have to test other wikisystems too ...

Thanks,
Silvio
