### ISSUE TITLE
UI Issue: Open Wiki page in new Tab

### ISSUE THREAD

**Issue by ppxl** [cloudogu/smeagol#83]
### Issue description

As I have several smeagol pages at hand, I have a hard time to open multiple repositories in a new tab. Wikis opened this way do not appear. The page is blank.

Is this a bug? Probably. Adding a slash inside the URL does the fix.

### Steps

1. Open smeagol
2. Browse the list of available wikis (must have content)
3. Open link to wiki in new tab (f. i. by context menu or mouse wheel click)
4. A page like `my.tld.com/smeagol88QYrgiYb1/` opens in the new tab. It keeps being blank.

### Fix

Convert the URL to `my.tld.com/smeagol/88QYrgiYb1/` (note the slash before the char salad)

**Comment by mbehlendorf** [comment]
The problem exists for wikipages as well as repositories. Furthermore the Link generation reacts sensitive to trailing slashes.
