### ISSUE TITLE
Which License is this under?

### ISSUE THREAD

**Issue by hoijui** [cloudogu/smeagol#90]
Hello! :-)
As there is no LICENSE file, and the source file headers only say "All rights reserved", I must assume that this is proprietary software. Am I right?
I am asking because usually, such software does not end up in the open on github, but it is often a mistake of not specifying the license, which of course, I am hoping for! :-)

**Comment by robertauer** [comment]
Hi!
Thanks for your question! We are working on the issue and will get back to you soon.

**Comment by ppxl** [comment]
Hey @hoijui, I've got good news for you. This repository is meant to be licensed under MIT license but it didn't went through the whole way. With an upcoming PR the license should be clear.

I hope this helps.

**Comment by hoijui** [comment]
niiiice! :-)
thanks you two, very good news indeed!
